### ISSUE TITLE
Spanish Press Release cannot have Spanish Articles as Related Resources

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1158]
In a Spanish Press Release, links to Spanish Articles don't render in the Related Resources section. (It works correctly for English.)

## The Easy Way

Add the following to the YAML file for a Spanish press release. After reprocessing the YAML content, the link doesn't appear.

```
  field_related_resources__ES:
    - entity: 'paragraph'
      type: "cgov_internal_link"
      field_internal_link:
        - target_type: 'node'
          '#process':
            callback: 'reference'
            args:
              - 'node'
              - type: 'cgov_article'
                title: 'Problemas de salud sexual en mujeres con cáncer'
```

## Via the User Interface

1. Login to www.devbox
1. Go to http://www.devbox/admin/content?title=&type=cgov_press_release&status=All&langcode=es
1. Edit an existing press release (e.g. [Informe Anual a la Nación: siguen descendiendo los índices de mortalidad por cáncer](http://www.devbox/espanol/node/103/edit?destination=/admin/content%3Ftitle%3D%26type%3Dcgov_press_release%26status%3DAll%26langcode%3DAll))
1. Scroll to "RELATED RESOURCES" (That should probably be "RECURSOS RELACIONADOS")
1. Click "Añadir Internal Link"
1. Expand "ENLACE (TODOS LOS IDIOMAS)"
1. Click "Select Content"
1. For "Titulo" enter "Problemas de salud sexual en mujeres con cáncer"
1. Click "Aplicar".
1. Select the article and click "Select content"
    * The article's _English_ title will now appear in the editing interface's list of resources.
1. Click "Guardar (esta traducción)
1. Click the article link in the notification on the top of the content list page.
1. Scroll to the bottom.  The article link does not appear.
