### ISSUE TITLE
Story: Support YAML Content Embeds

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2762]
## As a tester, I want the ability to add embedded elements into the YAML markup, so that I can build automation tests for our embedded content

> **ESTIMATE** NN

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Notes
* ...

---

## Technical Notes
* Embedded items use the UUID of content which is not something we can predict. We need to have some sort of way to set the `data-entity-uuid` attribute to a string that would map to a lookup.
* Entity Embed example (This is for an embedded image using the "right medium" template
   ```html
     <drupal-entity
        data-embed-button="media_entity_embed" 
        data-entity-embed-display="view_mode:media.image_display_article_medium"
        data-entity-type="media"
        data-entity- uuid="084f90fa-2aef-47d1-a377-e1a72d297801"
        data-align="right"
        data-caption=""
     ></drupal-entity>
   ```
* YAML Content Module Reference Field Process
   * Node
      ```
      field_featured_item:
         - target_type: 'node'
            '#process':
                 callback: 'reference'
                    args:
                       - 'node'
                       - type: 'cgov_article'
                          title: 'Frisco - The Roo Roo Kid'
      ```
   * Media
      ```
      field_image_article:
         - target_type: 'media'
            '#process':
                 callback: 'reference'
                    args:
                       - 'media'
                       - bundle: 'cgov_image'
                          name: 'Frisco - King of Shenandoah' 
      ```
   * Term ID
      ```
      field_site_section:
         - '#process':
            callback: 'reference'
            args:
                - 'taxonomy_term'
                - vid: 'cgov_site_sections'
                   computed_path: '/pets/frisco'
      ```

### Possible Solution 1: Use Regex
Use regex to replace the data-entity-uuid attribute with the correct UUID. This will follow the #process directive use for entity references.
```
<drupal-entity data-embed-button="media_entity_embed" data-entity-embed-display="view_mode:media.image_display_article_medium" data-entity-type="media" data-entity-uuid="#process('<PROCESS_TYPE>', '<ENTITY_TYPE>', '<BUNDLE>', '<CRITERIA>')" data-align="right" data-caption=""></drupal-entity>
```
Where the following parameters are:
* **PROCESS_TYPE** - The YAML content module's process type. This should probably just be `reference`
* **ENTITY_TYPE** - The type of entity, `node`, `media`, etc
* **BUNDLE** - The bundle for that entity, `cgov_article`, `cgov_image`, etc
* **CRITERIA** - this is a tricky bit and we don't want to make a full on language parser. In the yaml_content implementation these are the params passed to the entity query so it can lookup the entity. So we need some way to "serialize" the query, but without using any sort of quotes... so maybe `key:value|key:value` 

### Possible Solution 2: Use Dom Wrap
Use the DOMWrap package to process the HTML text on the YAML Content module's FieldImport event.  This will load the HTML into a DOM. It will find all the `<drupal-entity>` elements. Then get the parameters for the `#process` logic via attributes on the `<drupal-entity>`.

```html
<drupal-entity 
   data-embed-button="media_entity_embed"
   data-entity-embed-display="view_mode:media.image_display_article_medium"
   data-entity-type="media"
   data-entity-uuid="#process"
   data-align="right"
   data-caption=""
   data-cgov-yaml-query-*="<VALUE>"
></drupal-entity>
```
Where the following parameters are:
* **data-entity-uuid="#process"** - This tells us to process this entity and expect that we should be able to find all the other required attributes.
* **data-entity-type** - This is actually a drupal-entity attribute, but it is the entity type that is being embedded and is important for looking up the entity.
* **data-cgov-yaml-query-\*** - Additional parameters for the query, this should match the various queries done elsewhere in YAML content reference fields. (as referenced in the Technical Notes above. Examples would be:
  * Node
     * `data-cgov-yaml-query-type` - the bundle name
     * `data-cgov-yaml-query-title` - The node title
  * Media
     * `data-cgov-yaml-query-bundle` - the bundle name
     * `data-cgov-yaml-query-name` - the media items name

We should only do this for HTML fields, which should be of type `text_long`. And this would should only be done if the content contains a `<drupal-entity>` tag.

>**_NOTE:_** the `YamlContentEvents::IMPORT_FIELD` event is pretty much useless since you cannot modify the field data during that event. So this will have to modify the entity on `YamlContentEvents::ENTITY_PRE_SAVE.`
