### ISSUE TITLE
Drupal 9 does not support jQuery UI

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3193]
### Issue description
> **ESTIMATE** TBD

Drupal 9 has removed the jQuery UI library. There is a page describing the change and the new approach to take, https://www.drupal.org/node/3067969. I tried it out and `jquery_ui/widget` does not work, and we need widgets. So my thinking at this time is to bake jquery and jqueryUI into Common.js and be done with it. Hopefully core Drupal will not try and add jquery_ui.

In our `cgov_common.libraries.yml` file we reference the following dependencies in global. (We also reference jquery.ui elsewhere, which is kind of odd since every page gets common...)
```
  dependencies:
    - core/jquery
    - jquery_ui/core
    - jquery_ui/widget
    - jquery_ui_accordion/accordion
    - jquery_ui_dialog/dialog
    - jquery_ui_menu/menu
    - jquery_ui_selectmenu/selectmenu
    - jquery_ui_autocomplete/autocomplete
```

**Comment by bryanpizzillo** [comment]
## Approach
### Attempt 1:
As stated in the description of https://www.drupal.org/node/3067969, I installed all the modules we needed, and changed the theme dependencies.

### Attempt 2
This attempt will be to add jquery and jquery ui to our common.js using CDN. This is not exactly the "best" approach, although it does reduce the data downloaded through our CDN... I mean, let's be honest, the best approach is to not use either anymore... Anyway, I test this locally, and it appears to be a workable solution.

1. Remove all dependencies everywhere in `cgov_common.libraries.yml`
2. Add the following to the top of the `cgov_common.libraries.yml` file:
     ```
      jquery:
         remote: https://jquery.com
         version: 3.5.1
         license:
           name: MIT
           url: http://jquery.org/license/
           gpl-compatible: true
         js:
           //ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js: {type: external, minified: true }

      jquery-ui:
         remote: https://jqueryui.com
         version: 1.12.1
         license:
           name: MIT
           url: https://github.com/jquery/jquery-ui/blob/main/LICENSE.txt
           gpl-compatible: true
         js:
           //ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js: {type: external, minified: true }
         dependencies:
             - cgov_common/jquery
     ```
3. Add `cgov_common/jquery-ui` as a dependency of `global-scripts`.

An alternative to the CDN approach is to download a copy of jQuery and only the bits of jQueryUI that are needed, and make them a library entry. Additionally, we could make that bundle be an Entrypoint in web pack.
