### ISSUE TITLE
Enabler: Expose site nav as JSON API

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3243]
# Expose site nav as JSON API
> **ESTIMATE** Remaining story points 3 (continuing work in PR)

In order to support the mobile navigation we are defining for NCIDS/Redesign, we need to expose the navigable site sections. This API will support the two use cases we have identified for the Redesign navigation:
* Fetching the Mobile Menu - This would exclude all the sections that are marked as `hide_in_mobile_nav`
  * There are 2 occurrences of this tree, English and Spanish
* Fetching the Section Navs - This would exclude all the sections that are marked as `hide_in_section_nav` 
   * There are MANY occurrences of these items. (both in English and Spanish)

### Inputs
* `taxonomy_term` - the term ID of the Site Section to fetch, along with its children.
* Technically the menu type, but we will hard code this as part of the route. (`section-nav` or `mobile-nav`)
   * We will refer to this below as `menu_type` 

### Output

This will return a navigation item (let's call this NavItem) with the following structure:
```
{
  id: number, // The term id of the taxonomy node - this should be a unique id
  langcode: 'string', // The 2 char language code
  label: 'string', // This is the field_navigation_label field, or if empty, the name field
  weight: number, // The order of the term
  path: 'string', // The alias of the field_landing_page target
  navigation_display_options: [ ... parameters ... ], // the array of parameters
  is_section_nav_root: boolean, // true if this Site Section is a section nav root
  is_main_nav_root: boolean, // true if this Site Section is a main nav root
  children: [ ... NavItem ... ] // 0 or more NavItem objects
}
```

### Rules
1. Drupal will return the Site Section (the root), and its descendant Site Sections based on the rules for the provided `menu_type`.
    * NOTE: The Site Section taxonomy is hierarchical. **_If a term is excluded based on the filer, all of its descendants will be excluded as well._**
2. The root Site Section term is identified by the site section with the ID of `taxonomy_term`
    * This is the TID
    * The routes below 
3. The server shall return a 404 status if a Site Section cannot be found with the root_id. 
4. A Site Section (and its descendants) will be excluded if there is no referenced node in the `field_landing_page` field.
5. A Site Section (and its descendants) will be excluded if the referenced node in the `field_landing_page` field is not in a published state.
6. `menu_type` parameter rules
     * **mobile-nav**
        1. The server should return a 400 status code if the root Site Section's `field_main_nav_root` field is false.
        2. The server should return a 400 status code if the root Site Section's `field_landing_page` field is empty or unpublished.
        3. Descendants of the root Site Section will be excluded from the response if that descendant's `field_navigation_display_options` contains `hide_in_mobile_nav`
        4. The json response will have the cache tag of `nav_api_<menu_type>:<tid>`
        5. The tree of items returned should only be N levels deep, where N is the theme_get_setting('mobile_levels_to_display'), The default is 4 if the theme setting is not set.
        6. The root of the tree **does not** count in the levels to display as we do not display this in the UI.
     * **section-nav**
        1. The server should return a 400 status code if the root section's `field_section_nav_root ` field is false.
        2. The server should return a 400 status code if the root Site Section's `field_landing_page` field is empty or unpublished.
        3. Descendants of the root Site Section will be excluded from the response if that descendant's `field_navigation_display_options` contains `hide_in_section_nav`
        4. The json response will have the cache tag of `nav_api_<menu_type>:<tid>`
        5. The tree of items returned should only be N levels deep, where N is the root's `field_levels_to_display`. The default is 5 if the field is not set.
        6. The root of the tree **does** count in the levels to display as we do display it.        

## Approach
* Create a controller in the `cgov_site_section` module implementing these rules. The route will be:
   ```
   cgov_site_section.get_section_nav:
     path: '/taxonomy/term/{taxonomy_term}/section-nav'
     defaults:
       _controller: '\Drupal\cgov_site_section\Controller\CgovNavTreeController::getSectionNav'
       _title: 'section nav route'
     methods: [GET]
     requirements:
       _permission: 'access content'
       taxonomy_term: \d+
     options:
       parameters:
         taxonomy_term:
           type: entity:taxonomy_term
           bundle:
             - cgov_site_sections
   cgov_site_section.get_mobile_nav:
     path: '/taxonomy/term/{taxonomy_term}/mobile-nav'
     defaults:
       _controller: '\Drupal\cgov_site_section\Controller\CgovNavTreeController::getMobileNav'
       _title: 'mobile nav route'
     methods: [GET]
     requirements:
       _permission: 'access content'
       taxonomy_term: \d+
     options:
       parameters:
         taxonomy_term:
           type: entity:taxonomy_term
           bundle:
             - cgov_site_sections
   ```
* Update the cache clearing rules
   * A site section (or a node in the case of a site section's `field_landing_page` field) should only be considered as being modified if one of the fields checked in the original site section implement (#2206) was modified. I.E. use the existing rules to determine if a section was modified.
   * `section-nav`
      * A section-nav should be invalidated when a child section or landing page was modified that would appear in that nav. The section would appear if the follow are true:
         * The modified section Is no more than the `section-nav`'s `field_levels_to_display field` level deep.
            * For example: The Key Initiatives (`/research/key-initiatives') site section lists a depth of 1. If the section `/research/key-initiatives/ras/dialog` is modified, it would deeper than that nav and would NOT trigger an invalidation of the Key Initiatives section.
         * If the modified section's `field_navigation_display_options` does NOT contain `hide_in_section_nav`, NOR any ancestor's (i.e. parent) `field_navigation_display_options` contains `hide_in_section_nav` 
         * The section's field_landing_page must be set, and the target Node must be in a published state.
   * `mobile-nav`
      * A mobile-nav should be invalidated when a child section or landing page was modified that would appear in that nav. The section would appear if the follow are true:
         * The modified section Is no more than `theme_get_setting('mobile_levels_to_show`)` levels deep.
            * `theme_get_setting('mobile_levels_to_show`)` should be a NEW configuration option, that defaults to 4.
         * If the modified section's `field_navigation_display_options` does NOT contain `hide_in_mobile_nav`, NOR any ancestor's (i.e. parent) `field_navigation_display_options` contains `hide_in_mobile_nav` 
         * The section's field_landing_page must be set, and the target Node must be in a published state.
* Create a theme setting for `mobile_levels_to_display` in the cgov_common theme
   * The default setting for this should be 4
   * the `title` should be "Mobile navigation levels to display"
   * the `description` should be "Number of levels to display in the mobile nav"
   * NOTE: This should be added to the config/install default config AND a schema needs to be made
   * Question: do we need an update hook for this to get work properly after deploy to prod?
>**_NOTE:_** This code has to live side-by-side with the current navigation rules. So take care to ensure cache clearing rules are not adversely affected.
