### ISSUE TITLE
Enabler: Update drupal/core to v9.2.15

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3321]
# Update Drupal/core to v9.2.15

This is an update to bring in security fixes.

> **ESTIMATE** TBD

**Comment by ramu-nih** [comment]
Due to some phpcs validation errors, we temporarily disabled the php code sniffer rules for this update.

Added the below lines in blt.yml file.
```
# Disable phpcs.
disable-targets:
  validate:
    phpcs: true
```
