### ISSUE TITLE
Spike: Determine How to Combine NCIDS & Legacy CSS/JS

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3349]
## In order to figure out the page templates and changes to implement USWDS a developer needs to determine how to pull in legacy CSS for the main content area, but not affect the rest of the page. (I.e. don't break our NCIDS styles)
> **Estimate** *# point* 

Right now we have toyed with just wrapping legacy classes with a `.legacy {}` wrapper, and then adding a div for `.legacy`. This did not really work. So we are digging deeper to see how we might make this work. Part of this investigation has resulted in other tickets needing to be completed in order to continue this. (e.g., #3296, #3293)

### Expected Deliverables:
* I assume this will end up with the common.css and page templates that we will actually need, or enough information for a set of tickets.

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by olitharp-nci** [comment]
```twig
{% set page_type = 'node--type-' ~ node.bundle|clean_class %}

{{ page.ncids_banner }}
<!-- NOTIFICATIONS HERE -->
{{ page.ncids_header }}

<div id="page" class="grid-container">
  <div class="grid-row">
    <!-- Begin MAIN CONTENT AREA -->
    <div class="main-content {{ page_type }}" id="content" tabindex="0">
      <div class="row general-page-body-container collapse">
        <div class="large-12 columns">
          <div class="row">
            {{ page.ncids_breadcrumb }}
          </div> <!-- END "row" -->
        </div> <!-- END "large-12 columns" -->

        <div class="grid-row grid-gap">
          <div class="desktop:grid-col-3">
            <!-- SECTION NAVIGATION -->
            {% if page.ncids_sidenav %}
              {{ page.ncids_sidenav }}
            {% endif %}
          </div>
          {# TODO: technically if there is no left nav we change some of the classes below. #}
          <div class="desktop:grid-col-9">
            <div class="legacy">
              <div class="columns contentzone has-section-nav" id="main" tabindex="0" role="main">
                {{ page.content }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{{ page.ncids_footer }}
```



```scss
@charset "utf-8";

// Import ncids tokens so we can use it in other definitions.
$theme-image-path: 'uswds/dist/img';

// Base
@import '@nciocpl/ncids-css/scss/lib/normalize';
@import '@nciocpl/ncids-css/scss/packages/required';
@import '@nciocpl/ncids-css/scss/packages/global';

// Dependencies
@import 'uswds/dist/scss/base/accessibility'; // header
@import 'uswds/dist/scss/elements/typography/content'; // usa-prose, usa-intro(lede/lead)
@import '@nciocpl/ncids-css/scss/packages/utilities'; // page options responsive display

// Components
// TODO @import 'uswds/dist/scss/elements/typography/prose';
@import '@nciocpl/ncids-css/scss/components/usa-skipnav/usa-skipnav';
@import '@nciocpl/ncids-css/scss/components/usa-banner/nci-banner';
@import '@nciocpl/ncids-css/scss/components/usa-site-alert/all';
@import '@nciocpl/ncids-css/scss/components/usa-breadcrumb/breadcrumb';
@import '@nciocpl/ncids-css/scss/components/usa-sidenav/nci-sidenav';
@import '@nciocpl/ncids-css/scss/components/usa-footer/nci-big';

// TODO Keep as last import for now, there is a ordering bug
@import '@nciocpl/ncids-css/scss/components/nci-header/nci-extended';


/** Legacy mixin things **/
@import "~Core/styles/environments/percussion";
@import "~Core/styles/variables";
@import "~Core/styles/mixins";
@import "~Core/styles/fonts";
@import '~Core/styles/breakpoint-mixins';
@import "~Core/styles/placeholders";
@import "~Styles/sprites/svg-sprite"; //sprites are sometimes used in *_overrides files

.legacy {
  @import "~Core/styles/reset";
  /****************** NCI UTILITIES ********************/

  @import "~Core/styles/equalheights"; //added flexbox height support

  @import "~Core/styles/nci-foundation";
  /* @import "grid"; */ /* using this for override of foundation media screen if necessary */
  /***  END FOUNDATION STYLES ***/
  /***  BEGIN FOUNDATION OVERRIDE STYLES ***/
  @import "~Core/styles/foundation_overrides";
  /***  END FOUNDATION OVERRIDE STYLES ***/
  /***  BEGIN SLICK STYLES ***/
  @import "~Core/libraries/carousel/slick";
  /***  BEGIN SLICK STYLES ***/
  /***  BEGIN JQUERY UI STYLES ***/
  @import "~Core/styles/jqueryui";
  /***  END JQUERY UI STYLES ***/
  /***  BEGIN JQUERY UI OVERRIDE STYLES ***/
  @import "~Core/styles/jqueryui_overrides";
  /***  END JQUERY UI OVERRIDE STYLES ***/
  /****************** END VENDOR LIBRARIES SECTION ********************/

  /****************** NCI COMPONENTS SECTION ********************/
  // these styles override and extend Foundation SASS partials
  @import "~Core/styles/components/global";
  @import "~Core/styles/components/buttons";
  @import "~Core/styles/components/forms";
  @import "~Core/styles/components/icons";

  /****************** END NCI COMPONENTS SECTION ********************/

  @import "~Core/styles/general";
  @import "~Core/styles/header";
  @import "~Core/styles/language_bar";
  @import "~Core/styles/utilitynav";

  @import "~Core/styles/search";

  @import "~Core/styles/footer";

  @import "~Core/styles/mainContent";
  @import "~Core/styles/images";
  @import "~Core/styles/embedded-entity";
  @import "~Core/styles/banners";
  @import "~Core/styles/bodybanner";
  @import "~Core/libraries/accordion/accordion";
  @import "~Core/styles/tables";
  @import "~Core/styles/font_resizer";
  @import "~Core/libraries/modal/modal";
  @import "~Core/libraries/carousel/carousel";
  @import "~Core/libraries/backToTop/backToTop";
  @import "~Core/styles/contentTemplate";
  @import "~Core/styles/news";
  @import "~Core/styles/onthispage";
  @import "~Core/styles/institutions";
  @import "~Core/styles/ebookButtons";
  @import "~Core/styles/materials_to_share";
  @import "~Core/styles/lists";
  @import "~Core/styles/managed-lists";
  @import "~Core/styles/topicFeature";
  @import "~Core/styles/videos";
  @import "~Core/libraries/tooltips/referenceTooltip";
  @import "~Core/styles/errorPage";
  @import "~Core/styles/contact";
  // TODO: POST-MIGRATION: Couple nav styles with nav libraries.
  @import "~Core/styles/nav";
  @import "~Core/styles/pagination";
  @import "~Core/styles/image-video-carousel";
  @import "~Core/styles/flexVideoPreview";
  @import "~Core/styles/arrowLinks";

  @import "~Core/styles/checkbox";
  @import "~Core/styles/popups";
  @import '~Core/styles/tableSort';
  @import '~Core/styles/borderless-cards';
  @import '~Core/styles/alternating-lists';
  @import '~Core/styles/special-report-raw';
  @import '~Core/styles/title-first-feature-cards';
  // @import "~Core/styles/spinner";

  /****************** NCI ENHANCEMENTS SECTION ********************/
  @import "~Core/libraries/liveHelpPopup/popupPartial";
  // @import "AppModuleSpecific/cts/NCI.Delighters";
  /****************** END NCI ENHANCEMENTS SECTION ********************/


/* !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!  END RESPONSIVE STYLES SECTION  !-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-! */

/* PRINT STYLES --------------------------------- */
@import "~Core/styles/print";
/* END PRINT STYLES ----------------------------- */

/* HACK STYLES */
@import "~Core/styles/hacks";

@include bp(large-up) {
	.cthp-card-container .cthp-dropdown.more-info {
		// CSSNano minifiews z-indexes. Until we remove it, it means CSS files that don't
		// go through the same entry point will have issues with z-index mismatches after minification.
		// In order to get a z-index for the drop-down higher than other elements on the page (specifically
		// the youtube thumbnail in the current case) the rule for the z-index on this element has to be in the
		// same stylesheet as the elements we want it to sit above.
		// See nvcg.scss for the z-index on this element.

		ul {
			z-index: 11 !important;
		}
	}
}
/* END HACK STYLES */

// This is a partial waiting to be made, it comes from the PDQ page, but at least
// some of the styles (.brand-fda) are being used in InnerPages
// (https://www.cancer.gov/about-cancer/treatment/drugs/raloxifenehydrochloride for
// example). I'm moving it here to fix issues for QA and make sure it's not easily ignored.
// Nothing in this file should remain as floating code for long. Partials only. (BB - 2/2018)

/* new styles */
.trial-sites h4 {
	background: #E6E6E2;
	padding: 3px 0;
	/* font-size: 16px; */
}
.trial-sites h5 {
	color: #993333;
	font-size: 15px;
	margin: 10px 0;
}
.trial-sites h6 {
	/* font-size: 14px; */
	font-style: normal;
	margin: 5px 0 10px;
}
.trial-sites .two-columns {
	margin: 0 30px;
}
.definition-term {
	line-height: 1em;
}
.definition-term-image {
	display: inline-block;
	vertical-align: middle;
}
figure.definition-image {
	width: 25%;
	display: block;
}
table.drug-combination {
	margin-left: 0px; //removed 20px per OCEPROJECT-2527
	width: 100%;

	td {
		padding: 5px;

		&.drug-combo-letter {
			text-align: right;
			font-weight: bold;
		}
	}
}
.two-columns.brand-fda {
	width: 60%;
}
.brand-fda .column1 {
	font-weight: bold;
}
table.table-default tfoot td {
	border: none;
	font-style: normal;
	margin: 0;
	padding: 8px 10px;
	background: $caption-background;
	font-size: 14px;
	line-height: 1.5em;
	font-family: $montserrat-font-stack;
}
.dis-disclaimer {
}
/* end new styles */


// Temporary hack to allow blog-intro-text to be used on topic pages until templates are adjusted BB 3/2018
.key-intro {
	// The following two styles are contextual, they can either be implemented or overriden depending
	// on whether we keep them here. I prefer implemented which is why they are commented out but not
	// outright deleted yet.
	// width: 100%;
	// margin-bottom: 1em;
	padding: 1em 1.25em;
	border-left: 3px solid $purple;
	background-color: $white03;

	p {
		margin: 0;
		padding-bottom: 1em;
		font-size: 0.8em;
		font-family: $montserrat-font-stack;
	}
	p:last-child {
		padding: 0;
	}
}

// This is a hack to rehide the comment policy on pages that aren't blog post pages with comments.
// The redundant rule is being left in the blog partial until a final approach is determined (some
// backend issues may need to be resolved). If you find this comment unchanged in 6 months, just
// sigh, shake your head, and remove the redundant rule. BB 4/2018.

// NOTE: The comment below about all.js is out of date and possibly predates the encapsulation of the
// page specific templates. This feature now only works on BlogPostPages
.blog-comment-policy {
	display: none;
	// made visible by JavaScript if an element matching `#cgvCommentsSl` exists (i.e., if comments are enabled)
	// @see all.js
}

@include bp(small) {
	figure {
		&.image-small, &.image-medium, &.image-center {
      float: none;
			width: 100%;
			margin: 0 0 1em 0;
		}
	}
}


// Overrides for the Moderation Sidebar module.
body {
  .ui-dialog.ui-dialog-off-canvas {
    z-index: 9998;
  }

  .ui-dialog-off-canvas #drupal-off-canvas .button,
  .ui-dialog-off-canvas #drupal-off-canvas  button {
    min-height: 0;
  }

  .ui-dialog-off-canvas {
    box-sizing: border-box;
  }
}

@import "~Core/styles/drupal";

}
```
