### ISSUE TITLE
Enabler: Build source branch for PRs

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4430]
# Change workflow behavior to build Pull Requests against the source branch instead of the merge branch.

By default, the [checkout action](https://github.com/actions/checkout/) uses the commit which triggered the workflow.  For a pull request, this is [the commit of the branch that would result from the PR](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request) (the "merge branch").

Relevant text:
> Note that `GITHUB_SHA` for this event is the last merge commit of the pull request merge branch. If you want to get the commit ID for the last commit to the head branch of the pull request, use `github.event.pull_request.head.sha` instead.

The purpose of this change is to [build against the most recent commit of the branch the PR is coming from](https://github.com/actions/checkout/tree/9a9194f87191a7e9055e3e9b95b8cfb13023bb08?tab=readme-ov-file#checkout-pull-request-head-commit-instead-of-merge-commit).

Potentially, the cleanest way to do this is to have two checkout [steps with a condition](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif) similar to:

```yaml
      - name: Checkout branch from Github (Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout branch from Github (Not Pull Request)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4
```

> **ESTIMATE** TBD

### Resources:

- [Events that trigger workflows](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request)
- (`actions/checkout` examples](https://github.com/actions/checkout/tree/9a9194f87191a7e9055e3e9b95b8cfb13023bb08?tab=readme-ov-file#checkout-pull-request-head-commit-instead-of-merge-commit)
 

### Notes

**Caveat:**  This will result in tests checking that the code in the _from_ branch works.  It will _prevent_ tests from checking whether the combined code will work properly.
