### ISSUE TITLE
Enabler: Turn on Dependabot updates

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4704]
# Turn on automatic pull requests from Dependabot based on package updates.

The goal of this ticket is to have Dependabot create pull requests for significant updates to our dependencies.  This makes sure we find out when packages are updated or have vulnerabilities patched and also saves developer time on a routine task.

Before activating dependabot for a given package manifest, the packages affected should be brought up to date, otherwise a pull request will be generated to bring them up to date.  If absolutely necessary, it is possible to exclude specific packages from being checked, but this is a bad idea.

There are four groups of packages which to be watched:

- `ncids_trans`
- `pdq_glossifier` (can likely be combined with `ncids_trans`)
- `cypress`
- `composer.json` in the project root.

Sample `dependabot.yml`

```yaml
version: 2
updates:
  # Frontend / user interface
  - package-ecosystem: "npm"
    directories:
      - "docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/front-end"
      - "docroot/profiles/custom/cgov_site/modules/custom/pdq_glossifier"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "frontend"
    groups:
      frontend-updates:
        dependency-type: "production"
        applies-to: "version-updates"
      frontend-security:
        dependency-type: "production"
        applies-to: "security-updates"

  # Cypress Tests
  - package-ecosystem: "npm"
    directory: "tests/cypress"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "cypress"
    groups:
      cypress-updates:
        dependency-type: "production"
        applies-to: "version-updates"
      cypress-security:
        dependency-type: "production"
        applies-to: "security-updates"

```

> **ESTIMATE** TBD

### Resources:
- [Dependabot YAML options](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference)
- [Grouping PRs (versus one per update)](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates)
