### ISSUE TITLE
Spike: Turn on Dependabot updates for PHP-only

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4715]
## In order to begin using Dependabot updates, we need to determine whether we can turn them on for only one project at a time in a single ecosystem.

Since we have recently updated to Drupal 10.4.6, this may be an ideal time to start using Dependabot for PHP updates, but only if we can do so without also getting pull requests for the themes and cypress tests at the same time. 

> **Estimate** *1 point* 

### Expected Deliverables:

Steps for turning on Dependabot for a single project ("manifest") file.

### Additional Notes:
* note 1

### Results of Spike

Yes, this is possible.

**Steps:**

1. Add `.github/dependabot.yml` (see below) to the repository's `develop` branch.
   ** 🚨 DO THIS FIRST 🚨 **
2. On the repository's `Settings` > `Advanced Security` page:
   - Enable the Dependency Graph.
   - Enable Dependabot alerts
   - The `dependabot.yml` rules file does rest. 

**Caveats:**

- We'll need to exempt Dependabot from "OCPL Configuration Management Standards Check" workflow or all of its pull requests will fail.
- For a given manifest file, dependency updates can be grouped according to whether the updates are version updates, or security updates, however both checks can only be run on the same schedule.
- Dependabot will update `composer.json` in addition the `.lock` file. So even with the updates we already have, there is still an immediate update to be done (see below).

Dependabot proposed updates:

(It is possible to set up a list of packages to be ignored (e.g. `drupa/core-*`)

| Package | From | To |
| --- | --- | --- |
| [composer/installers](https://github.com/composer/installers) | `1.12.0` | `2.3.0` |
| drupal/address | `1.11.0` | `1.12.0` |
| drupal/autologout | `1.6.0` | `2.0.1` |
| drupal/config_perms | `2.1.0` | `2.3.0` |
| [drupal/core-composer-scaffold](https://github.com/drupal/core-composer-scaffold) | `10.4.6` | `11.1.7` |
| drupal/image_widget_crop | `2.4.0` | `3.0.0` |
| drupal/linkit | `6.1.6` | `7.0.4` |
| drupal/responsive_favicons | `2.0.1` | `3.0.0` |
| drupal/viewsreference | `2.0.0-beta6` | `2.0.0-beta10` |
| [eluceo/ical](https://github.com/markuspoerschke/iCal) | `0.18.0` | `2.14.0` |
| [kint-php/kint](https://github.com/kint-php/kint) | `3.3` | `6.0.1` |
| [scotteh/php-dom-wrapper](https://github.com/scotteh/php-dom-wrapper) | `2.0.5` | `3.0.1` |
| [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) | `2.6.9` | `5.6.2` |

**Proposed dependabots.yml configuration**

```yaml
version: 2

updates:

  # Weekly check for PHP dependency updates.
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      # The morning after Drupal security releases.
      interval: "weekly"
      day: "thursday"
      time: "05:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "PHP package updates"
    groups:
      composer-dependencies:
        dependency-type: "production"
        applies-to: "version-updates"
      composer-security:
        dependency-type: "production"
        applies-to: "security-updates"
    # Don't try to update Drupal core.
    ignore:
      - dependency-name: "drupal/core-*"
```
