### ISSUE TITLE
Technical Item: Create BLT Command to Load our User in ACE Environments

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#557]
## Description 

When we re-install drupal locally or on cloud environments the users table is wiped out and the admin account is reset to a unique user name and password. We need a custom BLT command to read a local YAML file in the operator's home directory, which contains:
1. The username and password for user 1
2. A list of user names, passwords and roles to load

```
admin:
   user: 'admin'
   pass: 'password'
additional_users:
   - user: 'zedd'
      pass: 'password'
      roles: 
         - 'content_author'
   - user: 'kyla'
      pass: 'password'
      roles: 
         - 'content_author'
         - 'content_editor'
```

*  Create the following: 
    * The custom BLT command: `cgov:users:load`
       * It will default to looking for the path to drupal-users.yml file in the blt.yml. (if possible who knows if we can have custom configs, but why not?)
          * This should be under a cgov key. 
       * This will set the admin account information, if the `admin` key exists.
          * It will only override the username if the `user` key exists
          * It will only override the password if the `pass` key exists
          * It should skip empty values for either key with a warning. (i.e. if someone has `user: ''` warn and skip setting username. If user is missing, skip setting user name, no warning)          
       * This will add the additional accounts, if the `additional-users` key is set
          * If any of the `user`, `pass` or `roles` keys are missing, the element is skipped with a warning.
    * A local development version of the user YML in `docker/web/runtime/drupal-users.yml`
* Modify:
   * Update the following scripts to call our custom command after deploying the artifact, but before loading content.
      * `hooks/common/post-code-deploy/post-code-deploy.sh`
      * `hooks/common/post-code-update/post-code-update.sh`
*  Configure the:
    * blt.yml file to indicate where drupal-users.yml lives (`cgov.drupal_users_file`)
    * Docker-compose.yml to mount the users file to the root user's home directory
* Additionally:
   * Install the drupal-user.yml on the ACE servers

Obviously this needs to be actually tested locally AND in a cloud environment.
