### ISSUE TITLE
YAML importer doesn't store URL alias field

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#680]
The error message is

> The "node" entity cannot have a URI as it does not have an ID

This code (from the API plugin which imports PDQ summaries) works:

```
    $node->set('path', ['alias' => $summary['url']]);
```

… but this causes the YAML imported to choke with the error message above unless it is commented out:

```
  path:
    alias:
      value: /types/childhood-cancers/hp/unusual-cancers-childhood-pdq
  path__ES:
    alias:
      value: /tipos/infantil/pro/canceres-infantiles-poco-comunes-pdq
```
