### ISSUE TITLE
Add custom commands to be added to local (host) ~/.bashrc or ~/.bash_profile from repo.   

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#97]
Add option to install custom code into host os's startup file, similar to how `composer init-cgov` concats to the startup file.

**Comment by blairlearn** [comment]
This can be accomplished via a bind mount in the `docker-compose.override.yml` file.

E.g. If the custom .bashrc file is stored in `~/my-custom-docker-bash.sh`, then the `docker-compose.override.yml` file would look something like this:

```
version: "3.7"

services:

  web:
    volumes:
      - ~/my-custom-docker-bash:/root/.bashrc
```

Note that in order to be a bind mount instead of a named (not locally mapped) volume, the left portion of the volume specification **must** begin with one of `~` (tilde), `.` (period), or `/` (forward-slash).
